#!/system/bin/sh
# ========================================
# init.d script for McByte jkSGS3
# ========================================

# SQLite database vaccum

# Frequent inserts, up$bbox dates, and deletes can cause the database file to become fragmented - where data for a single table or index is scattered around the database file.
# Running VACUUM ensures that each table and index is largely stored contiguously within the database file.
# In some cases, VACUUM may also reduce the number of partially filled pages in the database, reducing the size of the database file further.

# Changelog
#  v1.0 - (??/??/????) - original version
#  v1.1 - (06/01/2013) - run only every X seconds, default = 1 week (mcbyte_it)
#

bbox=/sbin/busybox
sqlite=/sbin/sqlite3

# Log file location
LOG_FILE=/data/sqlite.log

#Interval between SQLite3 runs, in seconds, 604800=1 week
RUN_EVERY=259200

# Get the last modify date of the Log file, if the file does not exist, set value to 0
if [ -e $LOG_FILE ]; then
	LASTRUN=`$bbox stat -t $LOG_FILE | $bbox awk '{print $14}'`
else
	LASTRUN=0
fi;

# Get current date in epoch format
CURRDATE=`$bbox date +%s`

# Check the interval
INTERVAL=$($bbox expr $CURRDATE - $LASTRUN)

# If interval is more than the set one, then run the main script
if [ $INTERVAL -gt $RUN_EVERY ];
then
	if [ -e $LOG_FILE ]; then
		rm $LOG_FILE;
	fi;
		
	$bbox echo "SQLite database VACUUM and REINDEX started at $( date +"%m-%d-%Y %H:%M:%S" )" | $bbox tee -a $LOG_FILE;

	for i in `$bbox find /d* -iname "*.db"`; do
		$sqlite $i 'VACUUM;';
		resVac=$?
		if [ $resVac == 0 ]; then
			resVac="SUCCESS";
		else
			resVac="ERRCODE-$resVac";
		fi;
		
		$sqlite $i 'REINDEX;';
		resIndex=$?
		if [ $resIndex == 0 ]; then
			resIndex="SUCCESS";
		else
			resIndex="ERRCODE-$resIndex";
		fi;
		$bbox echo "Database $i:  VACUUM=$resVac  REINDEX=$resIndex" | $bbox tee -a $LOG_FILE;
	done

	$bbox rm -R -f /data/log/* ;
	$bbox rm -R -f /data/tombstones/* ;
	$bbox rm -R -f /data/anr/* ;
	$bbox rm -R -f /data/lost+found/* ;
	$bbox rm -R -f /data/system/usagestats/* ;
	$bbox rm -R -f /data/system/dropbox/* ;
	$bbox rm -R -f /data/data/*/cache/* ;

	$bbox echo "SQLite database VACUUM and REINDEX finished at $( $bbox date +"%m-%d-%Y %H:%M:%S" )" | $bbox tee -a $LOG_FILE;
fi;
