#!/system/bin/sh

# Automatic ZipAlign by Wes Garner
# ZipAlign files in /data that have not been previously ZipAligned (using md5sum)
# Thanks to oknowton for the changes

# Changelog:
# 1.0 (11/30/09) Original
# 1.1 (12/01/09) Switched to zipalign -c 4 to check the apk instead of MD5 (oknowton)
# 1.2 (06/01/13) Run the main script only once every N days (default 7 days, 1 week) (mcbyte_it)

bbox=/sbin/busybox
zipalign=/sbin/zipalign

LOG_FILE=/data/ramdiskzipalign.log
#Interval between ZipAlign runs, in seconds, 604800=1 week
RUN_EVERY=259200

# Get the last modify date of the Log file, if the file does not exist, set value to 0
if [ -e $LOG_FILE ]; then
	LASTRUN=`$bbox stat -t $LOG_FILE | $bbox awk '{print $14}'`
else
	LASTRUN=0
fi;

# Get current date in epoch format
CURRDATE=`$bbox date +%s`

# Check the interval
INTERVAL=$($bbox expr $CURRDATE - $LASTRUN)

# If interval is more than the set one, then run the main script
if [ $INTERVAL -gt $RUN_EVERY ];
then
	if [ -e $LOG_FILE ]; then
		$bbox rm $LOG_FILE;
	fi;

	$bbox echo "Starting Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | $bbox tee -a $LOG_FILE;
	for apk in /data/app/*.apk ; do
		$zipalign -c 4 $apk;
		ZIPCHECK=$?;
		if [ $ZIPCHECK -eq 1 ]; then
			$bbox echo ZipAligning $($bbox basename $apk)  | $bbox tee -a $LOG_FILE;
			$zipalign -fv 4 $apk /cache/$($bbox basename $apk);

			if [ -e /cache/$($bbox basename $apk) ]; then
				$bbox cp -f -p /cache/$($bbox $bbox basename $apk) $apk  | $bbox tee -a $LOG_FILE;
				$bbox rm /cache/$($bbox basename $apk);
			else
				$bbox echo ZipAligning $($bbox basename $apk) Failed  | $bbox tee -a $LOG_FILE;
			fi;
		else
			$bbox echo ZipAlign already completed on $apk  | $bbox tee -a $LOG_FILE;
		fi;
	done;
	for apk in /system/app/*.apk ; do
		$zipalign -c 4 $apk;
		ZIPCHECK=$?;
		if [ $ZIPCHECK -eq 1 ]; then
			$bbox echo ZipAligning $($bbox basename $apk)  | $bbox tee -a $LOG_FILE;
			$zipalign -fv 4 $apk /cache/$($bbox basename $apk);

			if [ -e /cache/$($bbox basename $apk) ]; then
				$bbox cp -f -p /cache/$($bbox $bbox basename $apk) $apk  | $bbox tee -a $LOG_FILE;
				$bbox rm /cache/$($bbox basename $apk);
			else
				$bbox echo ZipAligning $($bbox basename $apk) Failed  | $bbox tee -a $LOG_FILE;
			fi;
		else
			$bbox echo ZipAlign already completed on $apk  | $bbox tee -a $LOG_FILE;
		fi;
	done;
	$bbox echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" | $bbox tee -a $LOG_FILE;
fi


